project:
  type: website
  render:
    - "*"
    - "!CLAUDE.md"
    - "!LICENSE.md"

website:
  title: "Parks Canada - Intermediate R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - setup.qmd
      - text: Modules
        menu:
          - workflows.qmd
          - git-github.qmd
          - data-manipulation.qmd
          - programming-functions.qmd
          - regex.qmd
          - programming-iteration.qmd
          - quarto.qmd

execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
    css: style.css
    toc: true
    
  revealjs: 
    height: 900
    width: 1600
    theme: [moon, slides.scss]
    highlight-style: a11y
    slide-number: true
    chalkboard: true
    revealjs-plugins:
      - editable
    filters:
      - editable
    footer: "[{{< fa house >}}](index.qmd)"
